version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci: github: "
    labels: []
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/doc"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci: doc: "
    labels: []
    groups:
      doc-deps:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /scripts/dts/python-devicetree
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /scripts
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /tests/net/lib/lwm2m/interop
    schedule:
      interval: daily
