autobranch:
  pattern: '{number}-{title}'
  length: 60
commit:
  message:
    patterns:
      - '^(([^:]+):)(\s([^:]+):)*\s(.+)$'
approvals:
  minimum: 1
  ignore: none
  pattern: "^(:\\+1:|👍)$"
  veto:
    pattern: "^(:\\-1:|👎)$"
specification:
  title:
    minimum-length:
      enabled: true
      length: 8
  body:
    minimum-length:
      enabled: true
      length: 8
  template:
    differs-from-body: true
