name: Pull Request Assigner Completion Workflow

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Pull Request Assigner"]
    types:
      - completed

permissions:
  contents: read

jobs:
  assignment:
    name: Pull Request Assignment
    runs-on: ubuntu-24.04
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Download artifacts
        id: download-artifacts
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          workflow: assigner.yml
          run_id: ${{ github.event.workflow_run.id }}
          if_no_artifact_found: ignore

      - name: Load PR number
        if: steps.download-artifacts.outputs.found_artifact == 'true'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            let fs = require("fs");
            let pr_number = Number(fs.readFileSync("./pr/NR"));
            core.exportVariable("PR_NUM", pr_number);

      - name: Check PR number
        if: steps.download-artifacts.outputs.found_artifact == 'true'
        id: check-pr
        uses: carpentries/actions/check-valid-pr@2e20fd5ee53b691e27455ce7ca3b16ea885140e8 # v0.15.0
        with:
          pr: ${{ env.PR_NUM }}
          sha: ${{ github.event.workflow_run.head_sha }}

      - name: Validate PR number
        if: |
          steps.download-artifacts.outputs.found_artifact == 'true' &&
          steps.check-pr.outputs.VALID != 'true'
        run: |
          echo "ABORT: PR number validation failed!"
          exit 1


      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt

      - name: Install Python packages
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Run assignment script
        env:
          GITHUB_TOKEN: ${{ secrets.ZB_PR_ASSIGNER_GITHUB_TOKEN }}
        run: |
          if [ -f "./pr/manifest_areas.json" ]; then
            ARGS="--areas ./pr/manifest_areas.json"
          else
            ARGS=""
          fi
          python3 scripts/set_assignees.py -P ${{ env.PR_NUM }} -M MAINTAINERS.yml -v \
            --repo ${{ github.event.repository.name }} ${ARGS}
