name: Pull Request Assigner

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    branches:
    - main
    - collab-*
    - v*-branch
  issues:
    types:
    - labeled

permissions:
  contents: read

jobs:
  assignment:
    name: Pull Request Assignment
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # to add assignees to pull requests
      issues: write        # to add assignees to issues

    steps:

      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.12

      - name: cache-pip-linux
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('scripts/requirements-actions.txt') }}
          restore-keys: |
            ${{ hashFiles('scripts/requirements-actions.txt') }}

      - name: install-packages
        run: |
          pip install -r scripts/requirements-actions.txt

      - name: Run assignment script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python --version
