name: Pull Request Assigner

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    branches:
    - main
    - collab-*
    - v*-branch
  issues:
    types:
    - labeled

permissions:
  contents: read

jobs:
  assignment:
    name: Pull Request Assignment
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    permissions:
      issues: write        # to add assignees to issues

    steps:
      - name: Check out source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: zephyrproject-rtos/action-python-env@main
        with:
          python-version: 3.12

      - name: west setup
        if: >
          github.event_name == 'pull_request'
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          west init -l . || true
          mkdir -p ./pr

      - name: Run assignment script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FLAGS="-v"
          FLAGS+=" -o ${{ github.event.repository.owner.login }}"
          FLAGS+=" -r ${{ github.event.repository.name }}"
          FLAGS+=" -M MAINTAINERS.yml"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            FLAGS+=" -P ${{ github.event.pull_request.number }} --manifest -c origin/${{ github.base_ref }}.."
            python3 scripts/set_assignees.py $FLAGS
            cp -f manifest_areas.json ./pr/
          elif [ "${{ github.event_name }}" = "issues" ]; then
            FLAGS+=" -I ${{ github.event.issue.number }}"
            python3 scripts/set_assignees.py $FLAGS
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            FLAGS+=" --modules"
            python3 scripts/set_assignees.py $FLAGS
          else
            echo "Unknown event: ${{ github.event_name }}"
            exit 1
          fi


      - name: Save PR number
        if: >
          github.event_name == 'pull_request'
        run: |
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: >
          github.event_name == 'pull_request'
        with:
          name: pr
          path: pr/

