name: Backport Issue Check

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - v*-branch

permissions:
  contents: read

jobs:
  backport:
    name: Backport Issue Check
    concurrency:
      group: backport-issue-check-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    if: github.repository == 'zephyrproject-rtos/zephyr'
    permissions:
      issues: read # to check if associated issue exists for backport

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.12

      - name: cache-pip
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('scripts/requirements-actions.txt') }}
          restore-keys: |
            ${{ hashFiles('scripts/requirements-actions.txt') }}

      - name: install-packages
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Run backport issue checker
        env:
          GITHUB_TOKEN: ${{ secrets.ZB_GITHUB_TOKEN }}
        run: |
          ./scripts/release/list_backports.py \
          -o ${{ github.event.repository.owner.login }} \
          -r ${{ github.event.repository.name }} \
          -b ${{ github.event.pull_request.base.ref }} \
          -p ${{ github.event.pull_request.number }}
