name: Coverity Code Scanning
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - v*-branch
      - collab-*
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  CoverityScanCode:
    if: github.repository_owner == 'zephyrproject-rtos'
    runs-on:
      group: zephyr-runner-v2-linux-x64-4xlarge
    container:
      image: ghcr.io/zephyrproject-rtos/ci-repo-cache:v0.28.0.20250523
      options: '--entrypoint /bin/bash'
    steps:
      - name: Print cloud service information
        run: |
          echo "ZEPHYR_RUNNER_CLOUD_PROVIDER = ${ZEPHYR_RUNNER_CLOUD_PROVIDER}"
          echo "ZEPHYR_RUNNER_CLOUD_NODE = ${ZEPHYR_RUNNER_CLOUD_NODE}"
          echo "ZEPHYR_RUNNER_CLOUD_POD = ${ZEPHYR_RUNNER_CLOUD_POD}"

      - name: Apply container owner mismatch workaround
        run: |
          # FIXME: The owner UID of the GITHUB_WORKSPACE directory may not
          #        match the container user UID because of the way GitHub
          #        Actions runner is implemented. Remove this workaround when
          #        GitHub comes up with a fundamental fix for this problem.
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Clone cached Zephyr repository
        continue-on-error: true
        run: |
          git clone --shared /repo-cache/zephyrproject/zephyr .
          git remote set-url origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Environment Setup
        run: |
          if [ "${{github.event_name}}" = "pull_request" ]; then
            git config --global user.email "bot@zephyrproject.org"
            git config --global user.name "Zephyr Builder"
            rm -fr ".git/rebase-apply"
            rm -fr ".git/rebase-merge"
            git rebase origin/${BASE_REF}
            git clean -f -d
            git log  --pretty=oneline | head -n 10
          fi
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

          west init -l . || true
          west config manifest.group-filter -- +ci,+optional
          west config --global update.narrow true
          west update --path-cache /repo-cache/zephyrproject 2>&1 1> west.update.log || west update --path-cache /repo-cache/zephyrproject 2>&1 1> west.update.log || ( rm -rf ../modules ../bootloader ../tools && west update --path-cache /repo-cache/zephyrproject)
          west forall -c 'git reset --hard HEAD'

          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-$( cat SDK_VERSION )" >> $GITHUB_ENV

      - name: Check Environment
        run: |
          cmake --version
          gcc --version
          cargo --version
          rustup target list --installed
          ls -la
          echo "github.ref: ${{ github.ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"

      - name: SCA Setup
        uses: zephyrproject-rtos/action-sca-setup@main
        with:
          tool-name: coverity
          install-dir: coverity
          s3-access-key-id: ${{ secrets.TOOLDIST_ACCESS_KEY }}
          s3-secret-access-key: ${{ secrets.TOOLDIST_SECRET_ACCESS_KEY }}

      - name: Set Up Python 3.12
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt

      - name: install-packages
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Check Env
        run: |
          export COVERITY_OUTPUT_DIR=${PWD}/cov-int
          ./scripts/twister -j 16 -p qemu_x86  -T tests/kernel/threads --build-only -v  -xZEPHYR_SCA_VARIANT=coverity

          tar -cJvf coverity-results.tar.xz cov-int

          ver=`git describe`
          echo "PAYLOAD_VERSION=${ver}" >> $GITHUB_ENV
          echo "PAYLOAD_DESC=${ver}" >> $GITHUB_ENV

      - name: Analyze
        uses: zephyrproject-rtos/action-sca-setup/analyze@main
        with:
          tool-name: coverity
          payload: coverity-results.tar.xz
          service: https://scan.coverity.com/builds?project=Zephyr+Testing
          user: ${{ secrets.COVERITY_USER }}
          token: ${{ secrets.COVERITY_TOKEN }}
          version: ${{ env.PAYLOAD_VERSION }}
          description: ${{ env.PAYLOAD_DESC }}
