name: Footprint Tracking

# Run every 12 hours and on tags
on:
  schedule:
    - cron: '50 1/12 * * *'
  push:
    paths:
      - 'VERSION'
      - '.github/workflows/footprint-tracking.yml'
    branches:
      - main
      - v*-branch
    tags:
      # only publish v* tags, do not care about zephyr-v* which point to the
      # same commit
      - 'v*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  footprint-tracking:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'zephyrproject-rtos'
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
    env:
      ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: zephyr
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt

      - name: Install Python packages
        working-directory: zephyr
        run: |
            pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_TESTING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TESTING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@f7b70269a8eb01f70c8e710891e4c94972a2f6b4 # v1.0.6
        with:
          app-path: zephyr
          toolchains: all

      - name: Install additional packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gperf

      - name: Record Footprint
        working-directory: zephyr
        env:
          BASE_REF: ${{ github.base_ref }}
        run: |
          export ZEPHYR_BASE=${PWD}
          ./scripts/footprint/track.py  -p scripts/footprint/plan.txt

      - name: Upload footprint data
        working-directory: zephyr
        run: |
          aws s3 sync  --quiet footprint_data/ s3://testing.zephyrproject.org/footprint_data/

      - name: Transform Footprint data to Twister JSON reports
        working-directory: zephyr
        run: |
          shopt -s globstar
          export ZEPHYR_BASE=${PWD}
          python3 ./scripts/footprint/pack_as_twister.py -vvv \
            --plan ./scripts/footprint/plan.txt \
            --test-name='name.feature' \
            ./footprint_data/**/

      - name: Upload to ElasticSearch
        working-directory: zephyr
        env:
          ELASTICSEARCH_KEY: ${{ secrets.ELASTICSEARCH_KEY }}
          ELASTICSEARCH_SERVER: "https://elasticsearch.zephyrproject.io:443"
          ELASTICSEARCH_INDEX: ${{ vars.FOOTPRINT_TRACKING_INDEX }}
        run: |
          shopt -s globstar
          run_date=`date --iso-8601=minutes`
          python3 ./scripts/ci/upload_test_results_es.py -r ${run_date} \
            --flatten footprint \
            --flatten-list-names "{'children':'name'}" \
            --transform "{ 'footprint_name': '^(?P<footprint_area>([^\/]+\/){0,2})(?P<footprint_path>([^\/]*\/)*)(?P<footprint_symbol>[^\/]*)$' }" \
            --run-id "${{ github.run_id }}" \
            --run-attempt "${{ github.run_attempt }}" \
            --run-workflow "footprint-tracking:${{ github.event_name }}" \
            --run-branch "${{ github.ref_name }}" \
            -i ${ELASTICSEARCH_INDEX} \
            ./footprint_data/**/twister_footprint.json
        #
