name: Manifest
on:
  pull_request:

permissions:
  contents: read

jobs:
  contribs:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # to create/update pull request comments
      issues: write
    name: Manifest
    steps:
      - name: Checkout the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: zephyrproject/zephyr
            #ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: west setup
        env:
          BASE_REF: ${{ github.base_ref }}
        working-directory: zephyrproject/zephyr
        run: |
          git checkout ${{ github.event.pull_request.head.sha }}
          pip install west
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          west init -l . || true

      - name: Manifest
        uses: zephyrproject-rtos/action-manifest@cb8f6fba6f20b5f8649bd573e80a7583a239894c # v1.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          manifest-path: 'west.yml'
          checkout-path: 'zephyrproject/zephyr'
          use-tree-checkout: 'true'
          check-impostor-commits: 'true'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest'
          dnm-labels: 'DNM (manifest)'
