on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  record_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: PR event
        run: |
          pip3 install pygithub
          python3 ./scripts/ci/merged_prs.py --pull-request ${{ github.event.pull_request.number }} --repo zephyrproject-rtos/zephyr-testing
