on:
	pull_request:
		branches:
			- main
		types: [closed]
jobs:
	record_merged:
		if: github.event.pull_request.merged == true
		runs-on: ubuntu-22.04
		steps:
      - name: PR event
        run: |
          echo ${{ github.event.pull_request }}
