name: Publish Twister Test Results

on:
  workflow_run:
    workflows: ["Run tests with twister"]
    branches:
      - main
    types:
      - completed

permissions:
  contents: read

jobs:
  upload-to-elasticsearch:
    if: |
      github.repository == 'zephyrproject-rtos/zephyr' &&
      github.event.workflow_run.event != 'pull_request'
    env:
      ELASTICSEARCH_KEY: ${{ secrets.ELASTICSEARCH_KEY }}
      ELASTICSEARCH_SERVER: "https://elasticsearch.zephyrproject.io:443"
    runs-on: ubuntu-22.04
    steps:
      # Needed for elasticearch and upload script
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.12

      - name: cache-pip
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('scripts/requirements-actions.txt') }}
          restore-keys: |
            ${{ hashFiles('scripts/requirements-actions.txt') }}

      - name: install-packages
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Download Artifacts
        id: download-artifacts
        uses: dawidd6/action-download-artifact@20319c5641d495c8a52e688b7dc5fada6c3a9fbc # v8
        with:
          path: artifacts
          workflow: twister.yml
          run_id: ${{ github.event.workflow_run.id }}
          if_no_artifact_found: ignore

      - name: Upload to elasticsearch
        if: steps.download-artifacts.outputs.found_artifact == 'true'
        run: |
          # set run date on upload to get consistent and unified data across the matrix.
          run_date=`date --iso-8601=minutes`
          if [ "${{github.event.workflow_run.event}}" = "push" ]; then
            python3 ./scripts/ci/upload_test_results_es.py -r ${run_date} \
            --run-attempt ${{github.run_attempt}} \
            --run-branch ${{github.ref_name}} \
            --index zephyr-main-ci-push-1 artifacts/*/*/twister.json
          elif [ "${{github.event.workflow_run.event}}" = "schedule" ]; then
            python3 ./scripts/ci/upload_test_results_es.py -r ${run_date} \
            --run-attempt ${{github.run_attempt}} \
            --run-branch ${{github.ref_name}} \
            --index zephyr-main-ci-weekly-1 artifacts/*/*/twister.json
          fi
